# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "cookieconsent-bar"
client_id = "29d87f1a8b60ed6411173338b47d047e"
application_url = "https://cookieconsent-bar-livid.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://cookieconsent-bar-livid.vercel.app/auth/callback",
  "https://cookieconsent-bar-livid.vercel.app/auth/shopify/callback",
  "https://cookieconsent-bar-livid.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-10"

[extensions.theme]
handle = "cookieconsent-extension"

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://cookieconsent-bar-livid.vercel.app/"
subpath = "cookieconsent-bar"
prefix = "apps"
